name: Yelb Docker Build, Push, Deploy & Cleanup

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Generate a Unique Image Tag (Using Short SHA)
    - name: Set image tag
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    # Step 4: Build and Push yelb-appserver Image
    - name: Build and Push yelb-appserver
      working-directory: yelb-appserver
      run: |
        docker build -t awsadmin009/yelb-images:yelb-appserver-${{ env.IMAGE_TAG }} .
        docker push awsadmin009/yelb-images:yelb-appserver-${{ env.IMAGE_TAG }}

    # Step 5: Build and Push yelb-db Image
    - name: Build and Push yelb-db
      working-directory: yelb-db
      run: |
        docker build -t awsadmin009/yelb-images:yelb-db-${{ env.IMAGE_TAG }} .
        docker push awsadmin009/yelb-images:yelb-db-${{ env.IMAGE_TAG }}

    # Step 6: Build and Push yelb-ui Image
    - name: Build and Push yelb-ui
      working-directory: yelb-ui
      run: |
        docker build -t awsadmin009/yelb-images:yelb-ui-${{ env.IMAGE_TAG }} .
        docker push awsadmin009/yelb-images:yelb-ui-${{ env.IMAGE_TAG }}

    # Step 7: Update `yelp-deploy.yaml` with latest image tags
    - name: Update `yelp-deploy.yaml` with latest image tags
      run: |
        sed -i "s|image: awsadmin009/yelb-images:yelb-appserver-.*|image: awsadmin009/yelb-images:yelb-appserver-${{ env.IMAGE_TAG }}|" yelp-deploy.yaml
        sed -i "s|image: awsadmin009/yelb-images:yelb-db-.*|image: awsadmin009/yelb-images:yelb-db-${{ env.IMAGE_TAG }}|" yelp-deploy.yaml
        sed -i "s|image: awsadmin009/yelb-images:yelb-ui-.*|image: awsadmin009/yelb-images:yelb-ui-${{ env.IMAGE_TAG }}|" yelp-deploy.yaml

    # Step 8: Commit and push updated `yelp-deploy.yaml`
    - name: Commit and push updated `yelp-deploy.yaml`
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.email "che80911@gmail.com"
        git config --global user.name "Cheson"
        git add yelp-deploy.yaml
        git diff --cached --quiet || (git commit -m "Update deployment file with latest image tags" && git push https://x-access-token:${GH_TOKEN}@github.com/adminaws009/myrepo.git HEAD:main)

    # Step 9: Set Up AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 10: Install eksctl
    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    # Step 11: Create EKS Cluster using eksctl
    - name: Create EKS Cluster with eksctl
      run: |
        eksctl create cluster -f eks-cluster.yaml
        eksctl utils wait-for-nodegroup --cluster yelb-cluster --nodegroup yelb-nodes --region ${{ secrets.AWS_REGION }}

    # Step 12: Update kubeconfig to connect to EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name yelb-cluster

    # Step 13: Deploy to EKS Cluster
    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f yelp-deploy.yaml

    # Step 14: Verify Deployment
    - name: Verify Deployment
      run: kubectl get pods -A

    # Step 15: (Optional) Delete the EKS Cluster After Deployment
    - name: Delete EKS Cluster
      if: always()
      run: |
        eksctl delete cluster --name yelb-cluster --region ${{ secrets.AWS_REGION }}
