apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1
  version: "1.27"

vpc:
  id: "" # Leave empty to automatically create a new VPC
  subnets: {}
  enableDNSSupport: true
  enableDNSHostnames: true

nodeGroups:
- name: node-group
  instanceType: t2.micro
  desiredCapacity: 4
  minSize: 4
  maxSize: 4
  ssh:
    allow: true
    publicKeyName: my-keypair # Replace with your SSH key pair

cloudWatch:
  clusterLogging:
    enableTypes: [ "api", "audit", "authenticator", "controllerManager", "scheduler" ]
