apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1
  version: "1.27"

fargateProfiles:
  - name: default
    selectors:
      - namespace: default

  - name: yelb
    selectors:
      - namespace: yelb
