name: Yelb Docker Build and Push

on:
  push:
    branches:
    - main # Runs workflow on push to the main branch
  pull_request:
    branches:
    - main # Runs workflow on pull requests to main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Generate a Unique Image Tag (Using Short SHA)
    - name: Set image tag
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    # Step 4: Build and Push yelb-appserver Image
    - name: Build and Push yelb-appserver
      working-directory: yelb-appserver
      run: |
        docker build -t awsadmin009/yelb-images:yelb-appserver-${{ env.IMAGE_TAG }} .
        docker push awsadmin009/yelb-images:yelb-appserver-${{ env.IMAGE_TAG }}

    # Step 5: Build and Push yelb-db Image
    - name: Build and Push yelb-db
      working-directory: yelb-db
      run: |
        docker build -t awsadmin009/yelb-images:yelb-db-${{ env.IMAGE_TAG }} .
        docker push awsadmin009/yelb-images:yelb-db-${{ env.IMAGE_TAG }}

    # Step 6: Build and Push yelb-ui Image
    - name: Build and Push yelb-ui
      working-directory: yelb-ui
      run: |
        docker build -t awsadmin009/yelb-images:yelb-ui-${{ env.IMAGE_TAG }} .
        docker push awsadmin009/yelb-images:yelb-ui-${{ env.IMAGE_TAG }}

    # Step 7: Output Image Tags
    - name: Show pushed image tags
      run: |
        echo "Pushed images:"
        echo "awsadmin009/yelb-images:yelb-appserver-${{ env.IMAGE_TAG }}"
        echo "awsadmin009/yelb-images:yelb-db-${{ env.IMAGE_TAG }}"
        echo "awsadmin009/yelb-images:yelb-ui-${{ env.IMAGE_TAG }}"
